# Generated by Django 4.1.6 on 2023-02-10 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='gust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.gust'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.movie'),
        ),
    ]
